In [2]:
import numpy as np

In [41]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [42]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

## 1) How many negative numbers are there?

In [5]:
neg_num = a[a < 0]
neg_num

array([-2, -1, -6, -7])

In [6]:
len(neg_num)

4

## 2) How many positive numbers are there?

In [7]:
pos_num = a[a > 0]
pos_num

array([ 4, 10, 12, 23,  3])

In [8]:
len(pos_num)

5

## 3) How many even positive numbers are there?

In [9]:
even_num = a[a % 2 == 0]
even_num

array([ 4, 10, 12, -2,  0,  0,  0, -6])

In [17]:
even_pos_num = a[(a % 2 == 0) & (a > 0)]
even_pos_num

array([ 4, 10, 12])

In [18]:
len(even_pos_num)

3

## 4) If you were to add 3 to each data point, how many positive numbers would there be?

In [19]:
plus_3 = a + 3
plus_3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [22]:
pos_plus_3 = plus_3[plus_3 > 0]
pos_plus_3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [23]:
len(pos_plus_3)

10

## 5) If you squared each number, what would the new mean and standard deviation be?

In [25]:
asquared = a ** 2
asquared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [26]:
mean_asquared = np.mean(asquared)
mean_asquared

74.0

In [27]:
std_asquared = np.std(asquared)
std_asquared

144.0243035046516

## 6) A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [28]:
center_asquared = asquared - mean_asquared
center_asquared

array([-58.,  26.,  70., 455., -70., -73., -74., -74., -74., -38., -65.,
       -25.])

In [30]:
mean_center_asquared = np.mean(center_asquared)
mean_center_asquared

0.0

## 7) Calculate the z-score for each data point. Recall that the z-score is given by:

Z=(x−μ)/σ


In [31]:
mean_a = np.mean(a)
mean_a

3.0

In [32]:
std_a = np.std(a)
std_a

8.06225774829855

In [33]:
z_score_a = (a - mean_a)/std_a
z_score_a

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## 8) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [44]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [60]:
sum_of_a = np.sum(a)
sum_of_a

55

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [61]:
min_of_a = np.min(a)
min_of_a

1

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [62]:
max_of_a = np.max(a)
max_of_a

10

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [63]:
mean_of_a = np.mean(a)
mean_of_a

5.5

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [64]:
product_of_a = np.product(a)
product_of_a

3628800

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [65]:
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [66]:
odd_in_a = a[a % 2 == 1]
odd_in_a

array([1, 3, 5, 7, 9])

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [67]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [68]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b

[[3, 4, 5], [6, 7, 8]]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0  
for row in b:  
sum_of_b += sum(row)  

In [69]:
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [79]:
sum_of_b = np.sum(b)
sum_of_b

33

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [80]:
min_of_b = np.min(b)
min_of_b

3

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [81]:
max_of_b = np.max(b)
max_of_b

8

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [82]:
mean_of_b = np.mean(b)
mean_of_b

5.5

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1  
for row in b:  
for number in row:  
product_of_b *= number  

In [83]:
product_of_b = np.product(b)
product_of_b

20160

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []  
for row in b:  
for number in row:  
squares_of_b.append(number**2)

In [84]:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
for number in row:
if(number % 2 != 0):
odds_in_b.append(number)

In [85]:
odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
for number in row:
if(number % 2 == 0):
evens_in_b.append(number)

In [86]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

# Exercise 9 - print out the shape of the array b.

In [87]:
print(b.shape)

(2, 3)


# Exercise 10 - transpose the array b.


In [88]:
transpose_b = np.transpose(b)
transpose_b

array([[3, 6],
       [4, 7],
       [5, 8]])

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [108]:
reshape_b = np.reshape(b, 6)
reshape_b

array([3, 4, 5, 6, 7, 8])

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [109]:
reshape_b = np.reshape(b, (6,1))
reshape_b

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [110]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [112]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

In [114]:
min_c = np.min(c)
min_c

1

In [116]:
max_c = c.max()
max_c

9

In [117]:
sum_c = c.sum()
sum_c

45

In [119]:
prod_c = np.product(c)
prod_c

362880

# Exercise 2 - Determine the standard deviation of c.


In [122]:
std_c = c.std()
std_c

2.581988897471611

# Exercise 3 - Determine the variance of c.


In [123]:
var_c = c.var()
var_c

6.666666666666667

# Exercise 4 - Print out the shape of the array c


In [124]:
print(c.shape)

(3, 3)


# Exercise 5 - Transpose c and print out transposed result.


In [125]:
transpose_c = c.transpose()
transpose_c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Exercise 6 - Get the dot product of the array c with c. 


In [126]:
dot_c = np.dot(c,c)
dot_c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [128]:
sum_dot_c = np.sum(dot_c)
sum_dot_c

729

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
